# Generated by Django 4.1 on 2022-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='static/home/images'),
            preserve_default=False,
        ),
    ]
