# Generated by Django 4.1 on 2022-12-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/home/images')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_image', models.ImageField(upload_to='static/home/images')),
                ('player1_name', models.CharField(max_length=255)),
                ('player1_image', models.ImageField(upload_to='static/home/images')),
                ('player2_name', models.CharField(max_length=255)),
                ('player2_image', models.ImageField(upload_to='static/home/images')),
                ('player3_name', models.CharField(max_length=255)),
                ('player3_image', models.ImageField(upload_to='static/home/images')),
                ('player4_name', models.CharField(max_length=255)),
                ('player4_image', models.ImageField(upload_to='static/home/images')),
                ('player5_name', models.CharField(max_length=255)),
                ('player5_image', models.ImageField(upload_to='static/home/images')),
                ('player6_name', models.CharField(max_length=255)),
                ('player6_image', models.ImageField(upload_to='static/home/images')),
                ('player7_name', models.CharField(max_length=255)),
                ('player7_image', models.ImageField(upload_to='static/home/images')),
                ('player8_name', models.CharField(max_length=255)),
                ('player8_image', models.ImageField(upload_to='static/home/images')),
                ('player9_name', models.CharField(max_length=255)),
                ('player9_image', models.ImageField(upload_to='static/home/images')),
                ('player10_name', models.CharField(max_length=255)),
                ('player10_image', models.ImageField(upload_to='static/home/images')),
                ('player11_name', models.CharField(max_length=255)),
                ('player11_image', models.ImageField(upload_to='static/home/images')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veneu', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='home.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='home.team')),
            ],
        ),
    ]
