# Generated by Django 4.1 on 2022-12-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.CharField(max_length=200),
        ),
    ]
