# Generated by Django 4.1 on 2023-01-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_match_team2_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=1000)),
                ('match_image', models.ImageField(upload_to='static/home/images')),
            ],
        ),
    ]
