# Generated by Django 4.1 on 2023-01-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_match_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_manager',
            field=models.CharField(default='admin', max_length=120),
            preserve_default=False,
        ),
    ]
